version: '3.6'
services:
  postgres:
    platform: linux/amd64
    image: mdillon/postgis:11
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_DB=testingwithrentals
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - ./sql-init.sql:/docker-entrypoint-initdb.d/sql-init.sql
      
  app:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=testingwithrentals
      - DB_USER=root
      - DB_PASSWORD=root
    ports: 
      - "8080:8080"
    restart: always
